# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'tbkmini nice_nano_v2 deep sleep'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["tbkmini_adapterv2_left","tbkmini_adapterv2_right"]'
      kconfig: '["CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1\nCONFIG_ZMK_SLEEP=y"]'
